### ISSUE TITLE
My form isn't coming in horizontal format like your screen

### ISSUE THREAD

**Issue by Ankita1996** [Devstackr/budget-app-angular#10]
![Screenshot (47)](https://user-images.githubusercontent.com/15686841/80943901-ea978280-8e05-11ea-9c59-7a261bb49c30.png)
I have installed bulma and have given the path of bulma (@import "../../Budget-app/node_modules/bulma";) in main-style.scss still my form isn't coming in horizontal format.
![Screenshot (46)](https://user-images.githubusercontent.com/15686841/80943864-cc318700-8e05-11ea-92f2-6d1e33e6656b.png)

Please check ss for reference,

**Comment by Devstackr8** [comment]
Hi Ankita, it looks like bulma hasn't been imported - it needs to be imported in `styles.scss`, as you can see in the source code: https://github.com/Devstackr/budget-app-angular/blob/a0f0c89133421043c14b180c38a9bc3b0ba53a4c/src/styles.scss#L4

I hope this helps - let me know if this fixes the issue 😃

**Comment by Ankita1996** [comment]
OMG! I literally forgot to put last few lines i.e bulma.sass. Thank you so much. It works

**Comment by Devstackr8** [comment]
Awesome, glad you got it working! 😃
